# ??. driver configuration
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

    #JPA config
    jpa:
      generate-ddl: false
      show-sql: true
      database: mysql
      properties:
        hibernate:
          format_sql: true
  #        '[format_sql]' : true
  mvc:
    static-path-pattern: /static/**


#  application:
#    name: fileupload
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#  mvc:
#    static-path-pattern: /static/**